name: 'Chrome Addon Action'
description: 'Upload your addon to the Chrome Web Store'
author: 'Thomas McNiven'
inputs:
  extension:
    description: 'ID of the extension that you are updating'
    required: true
  zip:
    description: 'Path to a .zip of your addon'
    required: true
  client-id:
    description: 'Google OAuth2 client id'
    required: true
  client-secret:
    description: 'Google OAuth2 client secret'
    required: false
  refresh-token:
    description: 'Google OAuth2 refresh token'
    required: true
  publish-target:
    required: false
    description: 'Chrome Store publish target "default" | "trustedTesters"'
    default: 'default'
runs:
  using: 'node12'
  main: 'dist/index.js'
